
export const SIGNUP_SIMPLE = 'SIGNUP_SIMPLE'
export const SINGUP_GOOLE = 'SIGNUP_GOOGLE'
export const CHANGTEXT_EMAIL = 'CHANGETEXT_EMAIL'
export const CHANGTEXT_PASSWORD = 'CHANGETEXT_PASSWORD'
export const CHANGTEXT_CONFIRM = 'CHANGETEXT_CONFIRM'
export const CHANGTEXT_MESSAGE = 'CHANGETEXT_MESSAGE'